# Import Library

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder 
from sklearn.preprocessing import OneHotEncoder

# Tampilkan Record

In [3]:
df = pd.read_csv('vgsales.csv')
df.head(100)

Rank                                    Name Platform    Year  \
0      1                              Wii Sports      Wii  2006.0   
1      2                       Super Mario Bros.      NES  1985.0   
2      3                          Mario Kart Wii      Wii  2008.0   
3      4                       Wii Sports Resort      Wii  2009.0   
4      5                Pokemon Red/Pokemon Blue       GB  1996.0   
..   ...                                     ...      ...     ...   
95    96  Crash Bandicoot 2: Cortex Strikes Back       PS  1997.0   
96    97                     Super Mario Bros. 2      NES  1988.0   
97    98     Super Smash Bros. for Wii U and 3DS      3DS  2014.0   
98    99              Call of Duty: World at War     X360  2008.0   
99   100                           Battlefield 3     X360  2011.0   

           Genre                    Publisher  NA_Sales  EU_Sales  JP_Sales  \
0         Sports                     Nintendo     41.49     29.02      3.77   
1       Platform                     Nintendo     29.08      3.58      6.81   
2         Racing                     Nintendo     15.85     12.88      3.79   
3         Sports                     Nintendo     15.75     11.01      3.28   
4   Role-Playing                     Nintendo     11.27      8.89     10.22   
..           ...                          ...       ...       ...       ...   
95      Platform  Sony Computer Entertainment      3.78      2.17      1.31   
96      Platform                     Nintendo      5.39      1.18      0.70   
97      Fighting                     Nintendo      3.24      1.35      2.42   
98       Shooter                   Activision      4.79      1.90      0.00   
99       Shooter              Electronic Arts      4.46      2.13      0.06   

    Other_Sales  Global_Sales  
0          8.46         82.74  
1          0.77         40.24  
2          3.31         35.82  
3          2.96         33.00  
4          1.00         31.37  
..          ...           ...  
95         0.31          7.58  
96         0.19          7.46  
97         0.43          7.45  
98         0.69          7.37  
99         0.69          7.34  

[100 rows x 11 columns]

# Bagi dataset menjadi training set dan testing set dengan proporsi 70:30


In [4]:
data  = df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']]
label = df['Publisher']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)


# Lakukan normalisasi data pada salah satu attribute menggunakan Min Max scaler

(buatlah copy dataset terlebih dahulu)

In [5]:
normalisasi = df.copy()
standarirasi = df.copy()

In [6]:
scaler = MinMaxScaler()

normalize_dataset = MinMaxScaler().fit_transform(normalisasi[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']])

In [7]:
normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.head(5)

0         1         2         3
0  1.000000  1.000000  0.368885  0.800378
1  0.700892  0.123363  0.666341  0.072848
2  0.382020  0.443832  0.370841  0.313150
3  0.379610  0.379394  0.320939  0.280038
4  0.271632  0.306340  1.000000  0.094607

# Lakukan standarisasi pada dataset

 (buatlah copy dataset terlebih dahulu)

In [8]:
standarirasi.drop(['Name','Platform','Year','Genre','Publisher'], axis=1, inplace=True)

standarirasi

Rank  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0          1     41.49     29.02      3.77         8.46         82.74
1          2     29.08      3.58      6.81         0.77         40.24
2          3     15.85     12.88      3.79         3.31         35.82
3          4     15.75     11.01      3.28         2.96         33.00
4          5     11.27      8.89     10.22         1.00         31.37
...      ...       ...       ...       ...          ...           ...
16594  16597      0.01      0.00      0.00         0.00          0.01
16595  16598      0.00      0.00      0.00         0.00          0.01
16596  16599      0.00      0.01      0.00         0.00          0.01
16597  16600      0.01      0.00      0.00         0.00          0.01
16598  16600      0.01      0.00      0.00         0.00          0.01

[16599 rows x 6 columns]

In [9]:
standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(standarirasi)

print('Dataset sebelum scalling:',  # SEBELUM
      f'Nilai standar deviasi:\n{np.std(standarirasi)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
Nilai standar deviasi:
Rank            4791.998211
NA_Sales           0.816636
EU_Sales           0.505322
JP_Sales           0.309273
Other_Sales        0.188577
Global_Sales       1.554940
dtype: float64

Dataset setelah scalling:
[[-1.73207603 50.48189995 57.13852348 11.93840962 44.60735711 52.86545473]
 [-1.73186735 35.28541502  6.79439322 21.7679256   3.8283476  25.53320406]
 [-1.73165867 19.08481102 25.19849744 12.00307748 17.29761732 22.69064999]
 [-1.73144999 18.96235747 21.49788724 10.35404684 15.44161559 20.87707477]
 [-1.73124131 13.47643866 17.30254305 32.79379714  5.04800588 19.82880257]
 [-1.73103263 28.08514657  4.18219778 13.39343665  2.8208038  19.11494849]]
Nilai standar deviasi: 1.0


# cek data null

In [10]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

# Lakukan Data cleaning pada data dengan nilai null 

In [11]:
standarisasi = df.copy()

standarisasi['Year'] = SimpleImputer(strategy='mean').fit_transform(standarisasi[['Year']])
standarisasi['Publisher'] =SimpleImputer(strategy='most_frequent').fit_transform(standarisasi[['Publisher']])

standarisasi.isna().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

# Lakukan Data cleaning pada data dengan nilai duplikat

cek data 

In [12]:
standarisasi.duplicated().sum()

1

drop data duplikat

In [13]:
standarisasi.drop_duplicates(inplace=True)

standarisasi.duplicated().sum()

0

# Ganti tipe data salah satu attribute angka

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16599 entries, 0 to 16598
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Rank          16599 non-null  int64  
 1   Name          16599 non-null  object 
 2   Platform      16599 non-null  object 
 3   Year          16328 non-null  float64
 4   Genre         16599 non-null  object 
 5   Publisher     16541 non-null  object 
 6   NA_Sales      16599 non-null  float64
 7   EU_Sales      16599 non-null  float64
 8   JP_Sales      16599 non-null  float64
 9   Other_Sales   16599 non-null  float64
 10  Global_Sales  16599 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB


# Ganti tipe data salah satu attribute angka

In [15]:
dat = {'Rank':float}
pd.options.display.float_format = '{:.1f}'.format
df['Rank'] = df['Rank'].astype('float64')

In [16]:
df.head(50)

Rank                                          Name Platform   Year  \
0    1.0                                    Wii Sports      Wii 2006.0   
1    2.0                             Super Mario Bros.      NES 1985.0   
2    3.0                                Mario Kart Wii      Wii 2008.0   
3    4.0                             Wii Sports Resort      Wii 2009.0   
4    5.0                      Pokemon Red/Pokemon Blue       GB 1996.0   
5    6.0                                        Tetris       GB 1989.0   
6    7.0                         New Super Mario Bros.       DS 2006.0   
7    8.0                                      Wii Play      Wii 2006.0   
8    9.0                     New Super Mario Bros. Wii      Wii 2009.0   
9   10.0                                     Duck Hunt      NES 1984.0   
10  11.0                                    Nintendogs       DS 2005.0   
11  12.0                                 Mario Kart DS       DS 2005.0   
12  13.0                   Pokemon Gold/Pokemon Silver       GB 1999.0   
13  14.0                                       Wii Fit      Wii 2007.0   
14  15.0                                  Wii Fit Plus      Wii 2009.0   
15  16.0                            Kinect Adventures!     X360 2010.0   
16  17.0                            Grand Theft Auto V      PS3 2013.0   
17  18.0                 Grand Theft Auto: San Andreas      PS2 2004.0   
18  19.0                             Super Mario World     SNES 1990.0   
19  20.0  Brain Age: Train Your Brain in Minutes a Day       DS 2005.0   
20  21.0                 Pokemon Diamond/Pokemon Pearl       DS 2006.0   
21  22.0                              Super Mario Land       GB 1989.0   
22  23.0                           Super Mario Bros. 3      NES 1988.0   
23  24.0                            Grand Theft Auto V     X360 2013.0   
24  25.0                   Grand Theft Auto: Vice City      PS2 2002.0   
25  26.0                 Pokemon Ruby/Pokemon Sapphire      GBA 2002.0   
26  27.0                   Pokemon Black/Pokemon White       DS 2010.0   
27  28.0   Brain Age 2: More Training in Minutes a Day       DS 2005.0   
28  29.0                        Gran Turismo 3: A-Spec      PS2 2001.0   
29  30.0                Call of Duty: Modern Warfare 3     X360 2011.0   
30  31.0       Pokémon Yellow: Special Pikachu Edition       GB 1998.0   
31  32.0                       Call of Duty: Black Ops     X360 2010.0   
32  33.0                           Pokemon X/Pokemon Y      3DS 2013.0   
33  34.0                     Call of Duty: Black Ops 3      PS4 2015.0   
34  35.0                    Call of Duty: Black Ops II      PS3 2012.0   
35  36.0                    Call of Duty: Black Ops II     X360 2012.0   
36  37.0                Call of Duty: Modern Warfare 2     X360 2009.0   
37  38.0                Call of Duty: Modern Warfare 3      PS3 2011.0   
38  39.0                          Grand Theft Auto III      PS2 2001.0   
39  40.0                       Super Smash Bros. Brawl      Wii 2008.0   
40  41.0                       Call of Duty: Black Ops      PS3 2010.0   
41  42.0                   Animal Crossing: Wild World       DS 2005.0   
42  43.0                                  Mario Kart 7      3DS 2011.0   
43  44.0                                        Halo 3     X360 2007.0   
44  45.0                            Grand Theft Auto V      PS4 2014.0   
45  46.0          Pokemon HeartGold/Pokemon SoulSilver       DS 2009.0   
46  47.0                                Super Mario 64      N64 1996.0   
47  48.0                                Gran Turismo 4      PS2 2004.0   
48  49.0                            Super Mario Galaxy      Wii 2007.0   
49  50.0     Pokemon Omega Ruby/Pokemon Alpha Sapphire      3DS 2014.0   

           Genre                    Publisher  NA_Sales  EU_Sales  JP_Sales  \
0         Sports                     Nintendo      41.5      29.0       3.8   
1       Platform                     Nintendo      29.1       3.6      

In [17]:
df['Genre'].value_counts()

Action          3316
Sports          2346
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         887
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
Name: Genre, dtype: int64

# Lakukan one hot encoding pada dataset.

Buat copy dataset

In [18]:
OneHot = df.copy()

df['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

In [19]:
temp_dataset = pd.get_dummies(OneHot[['Genre']])

temp_dataset = pd.DataFrame(temp_dataset)

OneHot.drop('Genre', axis=1, inplace=True)

OneHot = OneHot.join(temp_dataset)
OneHot.head(5)

Rank                      Name Platform   Year Publisher  NA_Sales  \
0   1.0                Wii Sports      Wii 2006.0  Nintendo      41.5   
1   2.0         Super Mario Bros.      NES 1985.0  Nintendo      29.1   
2   3.0            Mario Kart Wii      Wii 2008.0  Nintendo      15.8   
3   4.0         Wii Sports Resort      Wii 2009.0  Nintendo      15.8   
4   5.0  Pokemon Red/Pokemon Blue       GB 1996.0  Nintendo      11.3   

   EU_Sales  JP_Sales  Other_Sales  Global_Sales  ...  Genre_Fighting  \
0      29.0       3.8          8.5          82.7  ...               0   
1       3.6       6.8          0.8          40.2  ...               0   
2      12.9       3.8          3.3          35.8  ...               0   
3      11.0       3.3          3.0          33.0  ...               0   
4       8.9      10.2          1.0          31.4  ...               0   

   Genre_Misc  Genre_Platform  Genre_Puzzle  Genre_Racing  Genre_Role-Playing  \
0           0               0             0             0                   0   
1           0               1             0             0                   0   
2           0               0             0             1                   0   
3           0               0             0             0                   0   
4           0               0             0             0                   1   

   Genre_Shooter  Genre_Simulation  Genre_Sports  Genre_Strategy  
0              0                 0             1               0  
1              0                 0             0               0  
2              0                 0             0               0  
3              0                 0             1               0  
4              0                 0             0               0  

[5 rows x 22 columns]

In [20]:
OneHot.to_csv("vgsales After Clean.csv", index=False)