# import package yang dibutuhkan

In [1]:
import tensorflow as tf
import numpy as np

# 1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-0.3084377 , -0.1759316 , -0.31479242,  0.44143963, -1.8813374 ],
       [ 0.6806533 , -1.2121427 ,  0.24694769,  1.414203  ,  1.6754802 ],
       [ 0.49114624,  0.29385492, -1.0513381 , -1.4578646 ,  0.48081514],
       [ 0.30835485,  0.45044732,  0.54796386,  1.2633681 ,  1.6599778 ],
       [-0.75085205, -0.5010813 , -0.02773517,  1.4331723 ,  0.5807809 ]],
      dtype=float32)

# 2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [14]:
list_prime = [[2, 3, 5, 7, 11],
              [13, 17, 19, 23, 29],
              [31, 37, 41, 43, 47],
              [53, 59, 61, 71, 73],
              [79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

# 3. Tampilkan dimensi dari kedua variable tersebut

In [15]:
print("Dimensi Random Tensor : ",random_tensor.shape)
print("Dimensi Prime Tensor  : ",prime_tensor.shape)

Dimensi Random Tensor :  (5, 5)
Dimensi Prime Tensor  :  (5, 5)


# 4. perhitungan aritmetika 2 variable tersebut 

## - Penjumlahan

In [16]:
tf.add(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.6915623,  2.8240683,  4.6852074,  7.4414396,  9.118663 ],
       [13.680654 , 15.787857 , 19.246948 , 24.414204 , 30.67548  ],
       [31.491146 , 37.293854 , 39.94866  , 41.542137 , 47.480816 ],
       [53.308353 , 59.450447 , 61.547962 , 72.26337  , 74.65998  ],
       [78.249146 , 82.49892  , 88.97227  , 98.433174 ,  1.580781 ]],
      dtype=float32)>

## - Pengurangan

In [18]:
tf.subtract(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.3084378 ,  3.1759317 ,  5.3147926 ,  6.5585604 , 12.881337  ],
       [12.319346  , 18.212143  , 18.753052  , 21.585796  , 27.32452   ],
       [30.508854  , 36.706146  , 42.05134   , 44.457863  , 46.519184  ],
       [52.691647  , 58.549553  , 60.452038  , 69.73663   , 71.34002   ],
       [79.750854  , 83.50108   , 89.02773   , 95.566826  ,  0.41921908]],
      dtype=float32)>

## - Perkalian

In [19]:
tf.multiply(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -0.6168754 ,  -0.52779484,  -1.5739621 ,   3.0900774 ,
        -20.694712  ],
       [  8.848493  , -20.606426  ,   4.692006  ,  32.52667   ,
         48.58893   ],
       [ 15.2255335 ,  10.872632  , -43.104862  , -62.68818   ,
         22.598312  ],
       [ 16.342808  ,  26.576391  ,  33.425797  ,  89.699135  ,
        121.178375  ],
       [-59.31731   , -41.58975   ,  -2.46843   , 139.01772   ,
          0.5807809 ]], dtype=float32)>

## - Pembagian

In [20]:
tf.divide(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-6.48429155e+00, -1.70520821e+01, -1.58834829e+01,
         1.58572083e+01, -5.84690428e+00],
       [ 1.90992985e+01, -1.40247517e+01,  7.69393692e+01,
         1.62635765e+01,  1.73084698e+01],
       [ 6.31176567e+01,  1.25912476e+02, -3.89979210e+01,
        -2.94951935e+01,  9.77506638e+01],
       [ 1.71879898e+02,  1.30980911e+02,  1.11321213e+02,
         5.61989784e+01,  4.39764900e+01],
       [-1.05213806e+02, -1.65641785e+02, -3.20892212e+03,
         6.76820221e+01,  1.72181964e+00]], dtype=float32)>

## - Pangkat

In [21]:
tf.pow(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[8.0751574e-01, 8.2425064e-01, 6.0251731e-01, 2.3608031e+00,
        1.0984720e-02],
       [5.7307200e+00, 3.2249302e-02, 2.0691180e+00, 8.4286819e+01,
        2.8198041e+02],
       [5.4010310e+00, 2.8895073e+00, 2.0156676e-02, 4.1555078e-03,
        6.3675151e+00],
       [3.4016438e+00, 6.2758932e+00, 9.5125341e+00, 2.1818294e+02,
        1.2390093e+03],
       [3.7597831e-02, 1.0924105e-01, 8.8294435e-01, 7.0369800e+02,
        1.0000000e+00]], dtype=float32)>

# 5. Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [25]:
tf.argmax(random_tensor, axis=1).numpy()

array([3, 4, 0, 4, 3])

In [26]:

tf.argmin(random_tensor, axis=1). numpy() 

array([4, 1, 3, 0, 0])

In [27]:

tf.argmax(random_tensor, axis=0). numpy()

array([1, 3, 3, 4, 1])

In [28]:

tf.argmin(random_tensor, axis=0). numpy()

array([4, 1, 2, 2, 0])

# 6.Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [29]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()#penggabungan baris

array([[-3.0843771e-01, -1.7593160e-01, -3.1479242e-01,  4.4143963e-01,
        -1.8813374e+00],
       [ 6.8065327e-01, -1.2121427e+00,  2.4694769e-01,  1.4142030e+00,
         1.6754802e+00],
       [ 4.9114624e-01,  2.9385492e-01, -1.0513381e+00, -1.4578646e+00,
         4.8081514e-01],
       [ 3.0835485e-01,  4.5044732e-01,  5.4796386e-01,  1.2633681e+00,
         1.6599778e+00],
       [-7.5085205e-01, -5.0108129e-01, -2.7735170e-02,  1.4331723e+00,
         5.8078092e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
         1.0000000e+00]], dtype=float32)

# 7.Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [30]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 0.44143963, -0.1759316 , -0.3084377 , -0.31479242, -1.8813374 ],
       [ 1.6754802 ,  1.414203  ,  0.6806533 ,  0.24694769, -1.2121427 ],
       [ 0.49114624,  0.48081514,  0.29385492, -1.0513381 , -1.4578646 ],
       [ 1.6599778 ,  1.2633681 ,  0.54796386,  0.45044732,  0.30835485],
       [ 1.4331723 ,  0.5807809 , -0.02773517, -0.5010813 , -0.75085205]],
      dtype=float32)

In [31]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)